// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  ContextMenu: string;
  MenuItem: string;
  ansi: string;
  backToTop: string;
  error: string;
  fold: string;
  foldLine: string;
  foldOpen: string;
  hasError: string;
  lineNo: string;
  logBody: string;
  logFooter: string;
  logHeader: string;
  logLine: string;
  logMain: string;
  metaList: string;
  open: string;
}
export const cssExports: CssExports;
export default cssExports;
